package com.samplespace.device_order;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class userInformation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public userInformation() {
    }




}